-include /opt/build-harness/Makefile.prow

tests:
- artifact_dir: /tmp/artifacts
  as: sonar
  commands: |
    export SELF="make -f Makefile.prow"
    make -f Makefile.prow sonar/go/prow
  container:
    from: src
  secrets:
  - mount_path: /etc/sonarcloud/
    name: acm-sonarcloud-token

- artifact_dir: /tmp/artifacts
  as: unit
  commands: |
    export SELF="make -f Makefile.prow"
    make -f Makefile.prow unit-tests
  container:
    from: bin
